Added RDF module
BioDataFuse/pyBiodatafuse pull request #159
Opened 2024-08-21 14:30 UTC by jmillanacosta

Refactors the spaghetti code in the [test notebook](https://github.com/BioDataFuse/pyBiodatafuse/pull/141) into a module and adds notebook demonstrating how it works.

2024-08-30 11:51 UTC, jmillanacosta commented
Discuss:
- IRI patterns for the 9 node types
- how unique identifiers can be generated for each node type in each produced KG

2024-10-01 12:59 UTC, tabbassidaloii commented on src/pyBiodatafuse/constants.py
> +OPENTARGETS_DISEASE__COL = "OpenTargets_diseases"
remove extra `_`: OPENTARGETS_DISEASE_COL

2024-10-01 13:00 UTC, tabbassidaloii commented on src/pyBiodatafuse/constants.py
> -
please keep this in the constant file

2024-10-01 13:03 UTC, tabbassidaloii requested changes
see the comments on constants.py

2024-10-17 08:11 UTC, tabbassidaloii reviewed
Thank you @jmillanacosta. Please see my in line comments.
in general please try to call variables from contants file to make sure if they change latter, the changes would be reflected in other part of the codes as well

2024-10-17 08:11 UTC, tabbassidaloii commented on src/pyBiodatafuse/constants.py
> +OPENTARGETS_DISEASE_COL = "OpenTargets_diseases"
do you use this variable?
it is not currently used in the workflow
if you want it change it to
```
OPENTARGETS_DISEASE_COL = f"{OPENTARGETS}_diseases"
```

2024-10-17 08:11 UTC, tabbassidaloii commented on src/pyBiodatafuse/constants.py
> +DATA_SOURCES = {
call database names from the variable list, to make sure if they change latter, it would be reflected here too

2024-10-17 08:11 UTC, tabbassidaloii commented on src/pyBiodatafuse/graph/rdf.py
> +    for identifier_type in [
this could be called from constant file, to make sure if they change latter, it would be reflected here too

2024-10-17 12:19 UTC, jmillanacosta commented
> Thank you @jmillanacosta. Please see my in line comments. in general please try to call variables from contants file to make sure if they change latter, the changes would be reflected in other part of the codes as well

applied changes

2024-10-21 10:10 UTC, tabbassidaloii approved these changes

2024-10-21 10:45 UTC, merged